{% set name = "colcon-mixin" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e9304732d6cfa27cebb41ae03e3a241eca25d25caa6858275edc1ed838e49997

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - colcon-core >=0.12
    - python >={{ python_min }}
    - pyyaml

test:
  imports:
    - colcon_mixin
    - colcon_mixin.mixin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://colcon.readthedocs.io
  summary: Extension for colcon to read CLI mixins from files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j-rivero
    - Tobias-Fischer
    - wolfv
    - traversaro
