{% set name = "colcon-mixin" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colcon-mixin-{{ version }}.tar.gz
  sha256: e0c349cf7b07096128866ec10fa508e35400db208fecbbeb86a54ab1a1d49ee9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colcon-core >=0.12
    - python >=3.6
    - pyyaml

test:
  imports:
    - colcon_mixin
    - colcon_mixin.mixin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colcon.readthedocs.io
  summary: Extension for colcon to read CLI mixins from files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j-rivero
    - Tobias-Fischer
    - wolfv
    - traversaro
